spring:
  profiles:
    active: live
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 100MB

server:
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
